# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['shuffgauss', 'shuffgauss.test']

package_data = \
{'': ['*']}

install_requires = \
['numpy>=1.22.4,<2.0.0', 'scipy>=1.8.1,<2.0.0', 'tqdm>=4.64.0,<5.0.0']

setup_kwargs = {
    'name': 'shuffgauss',
    'version': '0.1.0',
    'description': 'A package to calculate shuffle gaussian mechanism.',
    'long_description': None,
    'author': 'spliew',
    'author_email': 'seng2pei@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<3.11',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
